version: '2'
services:
    proba2-app:
        image: proba2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://proba2-postgresql:5432/proba2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    proba2-postgresql:
        extends:
            file: postgresql.yml
            service: proba2-postgresql
